/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DialogComponent: typeof import('./src/components/DialogComponent.vue')['default']
    GetAnswer: typeof import('./src/components/GetAnswer.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    Huice: typeof import('./src/components/huice.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Roomlist: typeof import('./src/components/roomlist.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sign: typeof import('./src/components/Sign.vue')['default']
  }
}
